Revert "ARM: dts: msm: add DT properties for dynamic refresh for SDM660/SDM630"
-This reverts commit 0f0f8c61373bc1c7ad25d630dd2dff24220a5287.
--Also fixes the following error:
ERROR (phandle_references): Reference to non-existent node or label "dfps_data_mem"
ERROR: Input tree has errors.

Signed-off-by: KradKJ <kartikjadhav4001@gmail.com>