Revert "ARM: dts: msm: add DT properties for dynamic refresh for SDM660/SDM630"
-This reverts commit 1f9d195b19b8a251ac816ac8ea6842806946a4c2.
-Also fixes the following error:
ERROR (phandle_references): Reference to non-existent node or label "dfps_data_mem"
ERROR: Input tree has errors.

Signed-off-by: KradKJ <kartikjadhav4001@gmail.com>